### ISSUE TITLE
How to get account and password?

### ISSUE THREAD

**Issue by chenhengwei1999** [kaist-avelab/K-Radar_V1#2]
Hello, how can I get the account and password of this website (https://kaistavelab.direct.quickconnect.to:54568/)? Can the public download it for free now? Thank you in advance for your reply.

**Comment by DongHeePaek** [comment]
Hello, @chenhengwei1999.
The dataset will be opened around September 2022.
Since our dataset requires a large amount of memory (~13TB), we expect that setting up the server will take approximately two months.
In addition, the complete development kits (for training, evaluation, and visualization) and the code for the labeling and calibration program (in YouTube video) will be published around November 2022.

Thank you.

**Comment by lukasstaecker** [comment]
Hi, I'm looking forward to your dataset! I suspect the 4D tensors largely contribute to the 13TB memory. Can you provide an option to download the dataset without the 4D tensors to reduce required bandwidth and memory? Will you also provide the 4D radar pointclouds?

**Comment by DongHeePaek** [comment]
Hello, @lukasstaecker.
First of all, thank you for your interest in our research.
As we mention in the paper, we will provide "raw (i.e., pre-CFAR)" 4D radar tensors which are dense 4D matrices with power measurements in all elements along the dimensions.
This requires 13TB of memory and takes a few weeks to set up the server (i.e., compressing the data into zip files and uploading to the server).
Additionally, we will provide CFAR codes so that users can generate 4D radar point clouds from 4D radar tensors with different hyper-parameters (such as the number of training/guard cells).

Thank you.
